sudo: required
language: python
dist: trusty
python:
    - '3.5'

install:
  - pip install -U tox

env:
  matrix:
    - TESTENV=doc
    - TESTENV=py35
    - TESTENV=lint

script:
  - tox -e $TESTENV tests/
